identifier_name:
  excluded: # excluded via string array, include xyz for geometry operations.
    - id
    - x
    - y
    - z
    - ok

line_length:
  ignores_urls: true
  ignores_interpolated_strings: true

type_name:
  allowed_symbols:
    - "_"
  excluded:
    - ID
